<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgabu5d\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgabu5d/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNgabu5d.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNgabu5d\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNgabu5d\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ngabu5d',
    'container.build_id' => '856320e8',
    'container.build_time' => 1525298223,
));
